RRR_KdfUsage = {
    RRR_KdfUsage_Custom
    // RRR_KdfUsage_SuccessionNonce
    // RRR_KdfUsage_Fragment
}

RRR_KdfUsage_Custom = (
    custom: bstr, ; An arbitrary byte string
)

RRR_KdfUsage_SuccessionNonce = (
    succession_nonce: {},
)

RRR_KdfUsage_Fragment = (
    fragment: {
        usage: {
            RRR_KdfUsage_Fragment_Usage_Custom
            // RRR_KdfUsage_Fragment_Usage_EncryptionKey
            // RRR_KdfUsage_Fragment_Usage_FileName
            // RRR_KdfUsage_Fragment_Usage_FileTag
        },
        parameters: {
            record_nonce: uint,
            segment_index: uint,
            record_version: uint,
        },
    },
)

RRR_KdfUsage_Fragment_Usage_Custom = (
    custom: bstr, ; An arbitrary byte string
)

RRR_KdfUsage_Fragment_Usage_EncryptionKey = (
    encryption_key: {},
)

RRR_KdfUsage_Fragment_Usage_FileName = (
    file_name: {},
)

RRR_KdfUsage_Fragment_Usage_FileTag = (
    file_tag: {},
)
